name: prerender-service
services:
  - name: web
    source_dir: /
    github:
      repo: yourusername/prerender-service
      branch: main
    run_command: npm start
    build_command: npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: BASE_ORIGIN
        value: https://your-actual-website.com
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium