name: prerender-service
services:
  - name: web
    source_dir: /
    github:
      repo: electrichazem/prerender_2
      branch: main
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8000
    envs:
      - key: BASE_ORIGIN
        value: https://www.puzzle-technolog.com
      - key: PORT
        value: "8000"