name: prerender-service
services:
  - name: web
    source_dir: /
    github:
      repo: yourusername/prerender-service
      branch: main
    run_command: python app.py
    build_command: |
      pip install -r requirements.txt
      playwright install chromium
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8000
    envs:
      - key: BASE_ORIGIN
        value: https://www.puzzle-technology.com
      - key: PORT
        value: "8000"